version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: registardb
      POSTGRES_USER: registar_iam_user
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql

  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true" # Enables dashboard
      - "--providers.docker=true" # Enables Docker provider
      - "--entrypoints.web.address=:80" # Defines HTTP port
    ports:
      - "80:80" # HTTP
      - "8080:8080" # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Socket access

volumes:
  postgres_data: