# Generated by Django 6.0.2 on 2026-02-17 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
