# Generated by Django 6.0.2 on 2026-02-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registarapp', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
