# Generated by Django 6.0.2 on 2026-02-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registarapp', '0003_student_student_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
