# Generated by Django 6.0.2 on 2026-02-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registarapp', '0004_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address_line1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_line2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_contact',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='postcode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='previous_school',
            field=models.CharField(default='', max_length=200),
        ),
    ]
